#!/usr/bin/env bash

###
### To disable precommit hook: "git config precommit.disable 1"
###

### Settings ###

TS_JS_TYPES="\.(tsx?|jsx?)$"

### Lib ###

disable=`grep -Pzo '\[precommit\]\s+disable\s+=\s+1' .git/config &> /dev/null || false`
if [ "$disable" ]; then
  exit 0
fi

diff() {
  git diff-index --name-only HEAD --diff-filter ACMRTUXB
}

grepFiles() {
  res=`diff | grep -Ec "$1"`
  [[ $res == 0 ]] && return 1 || return 0
}

grepSrcFiles() {
  return `grepFiles "^src/.*\.($1)$"`
}

print() {
  printf "$1" "${@:2}"
}

println() {
  print "$1\n" "${@:2}"
}

msg() {
  print "[precommit] $1: $2" "${@:3}"
}

infom() {
  msg "info" "${@:1}"
}

info() {
  infom "$1\n" "${@:2}"
}

# Lint

if grepFiles "$TS_JS_TYPES"; then
  infom "Linting..."
  npm run --silent lint -- --quiet `diff | grep -P "$TS_JS_TYPES"` || exit 1
  println "done."
fi

# Dry compile

if grepFiles "$TS_JS_TYPES"; then
  infom "Dry compiling..."
  npm run compile -- --noEmit || exit 1
  println "done."
fi

# Test

if grepFiles "$TS_JS_TYPES"; then
  infom "Testing..."

  npm run test:src -- -o || exit 1

  println "done."
fi
